// <auto-generated />
using System;
using AutoWarm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoWarm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoWarm.Domain.Entities.GmailAccountDetails", b =>
                {
                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MailAccountId");

                    b.ToTable("GmailAccountDetails");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.MailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MailAccounts");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.SmtpImapAccountDetails", b =>
                {
                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImapHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImapPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImapPort")
                        .HasColumnType("int");

                    b.Property<bool>("ImapUseSsl")
                        .HasColumnType("bit");

                    b.Property<string>("ImapUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MailAccountId");

                    b.ToTable("SmtpImapAccountDetails");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupEmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("bit");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("MarkedAsImportant")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.ToTable("WarmupEmailLogs");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.ToTable("WarmupJobs");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<int>("DailyMaxEmails")
                        .HasColumnType("int");

                    b.Property<int>("DailyMinEmails")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxDurationDays")
                        .HasColumnType("int");

                    b.Property<double>("ReplyRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeWindowEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeWindowStart")
                        .HasColumnType("time");

                    b.Property<bool>("UseRandomization")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId")
                        .IsUnique();

                    b.ToTable("WarmupProfiles");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.GmailAccountDetails", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.MailAccount", "MailAccount")
                        .WithOne("GmailDetails")
                        .HasForeignKey("AutoWarm.Domain.Entities.GmailAccountDetails", "MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.MailAccount", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.User", "User")
                        .WithMany("MailAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.SmtpImapAccountDetails", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.MailAccount", "MailAccount")
                        .WithOne("SmtpImapDetails")
                        .HasForeignKey("AutoWarm.Domain.Entities.SmtpImapAccountDetails", "MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupEmailLog", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("WarmupEmailLogs")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupJob", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("WarmupJobs")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.WarmupProfile", b =>
                {
                    b.HasOne("AutoWarm.Domain.Entities.MailAccount", "MailAccount")
                        .WithOne("WarmupProfile")
                        .HasForeignKey("AutoWarm.Domain.Entities.WarmupProfile", "MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.MailAccount", b =>
                {
                    b.Navigation("GmailDetails");

                    b.Navigation("SmtpImapDetails");

                    b.Navigation("WarmupEmailLogs");

                    b.Navigation("WarmupJobs");

                    b.Navigation("WarmupProfile");
                });

            modelBuilder.Entity("AutoWarm.Domain.Entities.User", b =>
                {
                    b.Navigation("MailAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
